apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque
data:
  MONGO_INITDB_ROOT_USERNAME: dXNlcm5hbWU=
  MONGO_INITDB_ROOT_PASSWORD: cGFzc3dvcmQ= 

---
apiVersion: v1
kind: Secret
metadata:
  name: express-secret
type: Opaque
data:
  ME_CONFIG_MONGODB_ADMINUSERNAME: dXNlcm5hbWU=
  ME_CONFIG_MONGODB_ADMINPASSWORD: cGFzc3dvcmQ=